@startuml
object "<u>newHospital:Hospital</u>" as h2 {
id : String = "41-965-264"
name = Johns Hopkins
}

object "<u>newDepartment:Department</u>" as d2 {
id : String = "45-125-197"
name = Radiology
}
h2 "1" *-- "1..*" d2
@enduml
