@startuml
actor user
participant Theater
participant Server
user-> Theater: Insert card
user-> Theater: Select date
Theater --> user: Offer seat
user -> Theater :Submit order
Theater -> Server: Submit order 
Server -> Theater: Order Confirmed
Theater -> user: Order Confirmed
@enduml
