@startuml
skinparam classAttributeIconSize 0



interface "<<Interface>>\n Car" as Car
{
   # description:string
    +{abstract} getDescription():string
    +{abstract} getPrice():double;
}

class BaseModel
{
+ getPrice():double
}
note "return 35000" as BaseModelNote
BaseModelNote -left.. BaseModel

class OptionsDecorator
{
# m_car: Car*
+OptionsDecorator(Car *car)    
+{abstract} getPrice():double;
+{abstract} getDescription():string;
}

class Navigation
{
    getDescription():string
    getPrice():double;
}
class SoundSystem
{
    getDescription():string
    getPrice():double;

}
class LeatherSeat
{
    getDescription():string
    getPrice():double;
}
class Client{}
OptionsDecorator -up..|> Car
OptionsDecorator o-- Car

SoundSystem -up..|> OptionsDecorator
LeatherSeat -up..|> OptionsDecorator
Navigation -up..|> OptionsDecorator

BaseModel -up..|> Car
Client --> Car


note "Car *base_model=new BaseModel();\nCar *base_model_sound_system=new SoundSystem(base_model);\nCar *base_model_sound_system_navigan=new Navigation(base_model_sound_system);\nbase_model_sound_system_navigan->getDescription();\nbase_model_sound_system_navigan->getPrice()" as ClientNote


ClientNote -left--Client

note "return  m_car->getPrice()+  + 500;" as NavigationgetPrice
note "return  m_car->getDescription()+ ' + Navigation';" as NavigationgetDescription

NavigationgetDescription -- Navigation::getDescription
NavigationgetPrice -- Navigation::getPrice
@enduml
