@startuml
skinparam classAttributeIconSize 0

interface "<<interafce>> \n Button" as Button
{
+{abstract}  draw():void
}

interface "<<interafce>> \n Menu" as Menu
{
+{abstract}  draw():void
}

class LinuxButton{}
class LinuxMenu{}
class WindowsButton{}
class WindowsMenu{}

interface "<<interafce>> \n Factory" as Factory
{
    +{abstract} create_button(): *Button
    +{abstract} create_menu(): *Menu
}

class LinuxFactory
{
    + create_button(): *Button
    + create_menu(): *Menu
}
note  "return new LinuxButton" as LinuxFactorycreate_button
class WindowsFactory
{
    + create_button(): *Button
    + create_menu(): *Menu
}
note  "return new WindowsButton" as WindowsFactorycreate_button

LinuxButton -up..|> Button
LinuxMenu -up..|> Menu

WindowsButton -up..|> Button
WindowsMenu -up..|> Menu

LinuxFactory -up..|> Factory
WindowsFactory -up..|> Factory

WindowsFactorycreate_button -up..WindowsFactory
LinuxFactorycreate_button -up..LinuxFactory

class Client{}
Client--Button
Client--Menu
Client--Factory
@enduml
