@startuml
skinparam classAttributeIconSize 0
interface "<<interface>>\n Player" as Player
{
+   {abstract}  play():void
+   {abstract}  stop() :void
+   {abstract}  pause() :void
+   {abstract}  reverse() :void
}
interface "<<interface>>\n Recorder" as Recorder
{
+   {abstract} record():void
}
class TapePlayer
{
 play():void
 stop():void
 pause():void
 reverse():void
 record():void
}
Recorder <|-- TapePlayer
Player <|-- Recorder
@enduml
