name: Windows Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release, Debug]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 3.28.0

      - name: Configure CMake
        run: cmake --preset ninja-multi

      - name: Build with CMake
        run: |
          if ("${{ matrix.configuration }}" -eq "Debug") { cmake --build --preset ninja-multi-debug }
          if ("${{ matrix.configuration }}" -eq "Release") { cmake --build --preset ninja-multi-release }
